# Generated by Django 3.2.6 on 2021-08-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_whosepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='posts/media/posts', verbose_name='Photo'),
        ),
    ]
